OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "your_openai_api_key"
  target_language: "中文"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "test/test.pdf"
  file_format: "markdown"